\connect postgres
DROP DATABASE dokohome;
CREATE DATABASE dokohome ENCODING 'UTF8' LC_COLLATE 'C' TEMPLATE 'template0' OWNER 'doko';
\connect dokohome doko
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_topology;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS postgis_tiger_geocoder;
CREATE SCHEMA AUTHORIZATION doko;

