CREATE USER gis WITH SUPERUSER PASSWORD 'gis';
CREATE DATABASE gistest ENCODING 'UTF8' LC_COLLATE 'C' TEMPLATE 'template0' OWNER 'gis';
\connect gistest
CREATE EXTENSION postgis;
CREATE SCHEMA AUTHORIZATION gis;

